name: Terraform Validate
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

tf-validate:
  sync:
    uses: hashicorp/hvd-module-gha/.github/workflows/terraform-validate.yml@main
